"""add_resolved_by_pr_to_failures

Revision ID: 22b5b9f8b2c5
Revises: 66f3940c5a9b
Create Date: 2026-02-13 13:26:38.749725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b5b9f8b2c5'
down_revision: Union[str, None] = '66f3940c5a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failures', sa.Column('resolved_by_pr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failures', 'resolved_by_pr')
    # ### end Alembic commands ###
