"""add retry_success_count to error_signatures

Revision ID: 66f3940c5a9b
Revises: cba2626add08
Create Date: 2026-02-13 11:38:29.006115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f3940c5a9b'
down_revision: Union[str, None] = 'cba2626add08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error_signatures', sa.Column('retry_success_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error_signatures', 'retry_success_count')
    # ### end Alembic commands ###
