"""add failing_test column

Revision ID: cba2626add08
Revises: 5ab1a3c6acdb
Create Date: 2026-02-13 10:22:44.438850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba2626add08'
down_revision: Union[str, None] = '5ab1a3c6acdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failures', sa.Column('failing_test', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failures', 'failing_test')
    # ### end Alembic commands ###
